platform :ios, '13.0'

target 'KinoLib' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for KinoLib
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'

  pod 'Hex'

  pod 'PinLayout', '~> 1.10'
  pod 'Kingfisher', '~> 7.1'

end
